### ISSUE TITLE
Dataset folder

### ISSUE THREAD

**Issue by hujinhan12** [cake-lab/Xihe#1]
Hi Yiqin,

One quick question about the location of the dataset.

You mentioned that a pre-generated testing dataset is provided at the data/dataset/ directory. However, I cannot find that directory in this repo. Is there a link that I can download or preview them?

Thank you very much.

**Comment by YiqinZhao** [comment]
Hi Jinhan. Thanks for your interests in Xihe. We provide dataset link via email. I have sent the dataset link email to your ASU email address. Please check your mailbox and let me know if you have any questions.

**Comment by hujinhan12** [comment]
Hi Yiqin,

Great! Thanks. I just found the link, it's in my spam folder.

Best regards,

Jinhan Hu
